services:
  api:
    build:
      context: .
      dockerfile: src/PdfExtractor.WebApi/Dockerfile
    environment:
      PORT: 80
      Configuracao__CaminhoStorage: "/storage"
      Configuracao__ConexaoRedis: "redis:6379"
    ports:
      - "5000:80"
    volumes:
      - ./storage:/storage
    links:
      - redis
  worker:
    build:
      context: .
      dockerfile: src/PdfExtractor.Worker/Dockerfile
    environment:
      Configuracao__CaminhoStorage: "/storage"
      Configuracao__ConexaoRedis: "redis:6379"
    volumes:
      - ./storage:/storage
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
