services:
  api:
    build:
      context: .
      dockerfile: src/PdfExtractor.WebApi/Dockerfile
    environment:
      PORT: 80
      Configuracao__ConexaoPostgres: "Host=postgres;Port=5432;Database=PdfExtractor;User Id=postgres;Password=postgres1234;"
      Configuracao__CaminhoStorage: "/storage"
      Configuracao__ConexaoRedis: "redis:6379"
    ports:
      - "5000:80"
    volumes:
      - ./volumes/storage:/storage
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis
  worker:
    build:
      context: .
      dockerfile: src/PdfExtractor.Worker/Dockerfile
    environment:
      Configuracao__ConexaoPostgres: "Host=postgres;Port=5432;Database=PdfExtractor;User Id=postgres;Password=postgres1234;"
      Configuracao__CaminhoStorage: "/storage"
      Configuracao__ConexaoRedis: "redis:6379"
      Configuracao__TempoIntervaloProcessamento: 1000
    volumes:
      - ./volumes/storage:/storage
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis
  migration_runner:
    build:
      context: .
      dockerfile: src/PdfExtractor.Migrations.Runner/Dockerfile
    environment:
      Configuracao__ConexaoPostgres: "Host=postgres;Port=5432;Database=PdfExtractor;User Id=postgres;Password=postgres1234;"
      Configuracao__QtdeTentativas: 5
    links:
      - postgres
    depends_on:
      - postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: PdfExtractor
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
